### ISSUE TITLE
Custom Styling input[type="file"]

### ISSUE THREAD

**Issue by heron2014** [learnTrack/Q-A#71]
Example:

``` html
<form class='' action="/cv/upload" method="post" enctype="multipart/form-data">
          <input type="file" name="" class="custom-file-input" required>
          <button type="submit">Upload</button>
 </form>
```

``` css
.custom-file-input::-webkit-file-upload-button {
  visibility: hidden;
}

input.custom-file-input {
  outline: none;
}

.custom-file-input::before {
  content: 'Browse';
  display: inline-block;
  background-color: #424A5D;
  color: #FFD777;
  border: none;
  padding: 5px 8px;
  outline: none;
  -webkit-user-select: none;
  cursor: pointer;
}

```
